IGBT_view/IGBT_view/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from igbt.views import Home


urlpatterns = [
    url(r'^$', Home.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('igbt.urls')),
]

IGBT_view/igbt/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'igbt'

urlpatterns = [
    url(r'login/$', auth_views.login, name='login'),
    url(r'logout/$', auth_views.logout,
        {'template_name': 'registration/logout.html'}, name='logout'),
    url(r'password_change/$', auth_views.password_change,
        {'post_change_redirect': 'igbt:password_change_done',
         'template_name': 'registration/password_change.html'},
        name='password_change'),
    url(r'password_change/done/$', auth_views.password_change_done,
        {'template_name': 'registration/password_change_successfully.html'},
        name='password_change_done'),
    url(r'json_znp/$', json_znp),
    url(r'home/$', Start_page.as_view(), name='home'),
    url(r'igbt/$', Page_of_choice.as_view(), name='igbt_choice'),
    url(r'igbt/static_cold_measurements/$', Igbt_static_cold_modules.as_view(),
        name='igbt_static_cold_modules'),
    url(r'igbt/static_hot_measurements/$', Igbt_static_hot_modules.as_view(),
        name='igbt_static_hot_modules'),
    url(r'igbt/dinamic_cold_measurements/$',
        Igbt_dinamic_cold_modules.as_view(), name='igbt_dinamic_cold_modules'),
    url(r'igbt/dinamic_hot_measurements/$', Igbt_dinamic_hot_modules.as_view(),
        name='igbt_dinamic_hot_modules'),
    url(r'igbt/static_cold_measurements/(?P<pk>\d+_\d{4}(_\d){0,1})/$',
        Igbt_static_cold_module.as_view(), name='igbt_static_cold_module'),
    url(r'igbt/static_hot_measurements/(?P<pk>\d+_\d{4}(_\d){0,1})/$',
        Igbt_static_hot_module.as_view(), name='igbt_static_hot_module'),
    url(r'igbt/dinamic_cold_measurements/(?P<pk>\d+_\d{4}(_\d){0,1})/$',
        Igbt_dinamic_cold_module.as_view(), name='igbt_dinamic_cold_module'),
    url(r'igbt/dinamic_hot_measurements/(?P<pk>\d+_\d{4}(_\d){0,1})/$',
        Igbt_dinamic_hot_module.as_view(), name='igbt_dinamic_hot_module'),
    url(r'xlsx_export/$', Xlsx_export.as_view(), name='xlsx'),
]

IGBT_view/igbt/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class CommonIGBT(models.Model):

    znp = models.CharField(max_length=25, primary_key=True)
    time = models.DateTimeField()
    module_type = models.CharField(max_length=20)
    temperature = models.CharField(max_length=5)
    test_config = models.CharField(max_length=50)
    protocol_object = models.TextField()

    class Meta:
        abstract = True


class IGBT_static_cold (CommonIGBT):

    class Meta():
        db_table = 'igbt_static_cold'
        ordering = ('-time',)

    def __str__(self):
        return self.znp


class IGBT_static_hot (CommonIGBT):

    class Meta():
        db_table = 'igbt_static_hot'
        ordering = ('-time',)

    def __str__(self):
        return self.znp


class IGBT_dinamic_cold (CommonIGBT):

    class Meta():
        db_table = 'igbt_dinamic_cold'
        ordering = ('-time',)

    def __str__(self):
        return self.znp


class IGBT_dinamic_hot (CommonIGBT):

    class Meta():
        db_table = 'igbt_dinamic_hot'
        ordering = ('-time',)

    def __str__(self):
        return self.znp


class IGBT_module_types (models.Model):

    class Meta():
        db_table = 'igbt_module_types'

    module_type = models.CharField(max_length=20, primary_key=True)

    def __str__(self):
        return self.module_type


class Profile(models.Model):

    class Meta():
        db_table = 'profile'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    patronymic = models.CharField(max_length=20, blank=True)
    post = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

IGBT_view/igbt/forms.py
from django import forms
from .models import IGBT_module_types


sorting_list = [['-time', 'убыванию дыты'],
                ['time', 'возрастанию даты'],
                ['-znp', 'убыванию ЗНП'],
                ['znp', 'возрастанию ЗНП'],
                ]


def find_module_type():

    no_repeat_module_type_list = list(IGBT_module_types.objects.values_list(
        'module_type', flat=True))
    no_repeat_module_type_list.sort()
    no_repeat_module_type_list.insert(0, '')
    return [[x, x] for x in no_repeat_module_type_list]


class Filtr(forms.Form):

    date_1 = forms.DateTimeField(required=False, label='Период с',
                                 input_formats=['%d.%m.%Y', ])
    date_2 = forms.DateTimeField(required=False, label='Период до',
                                 input_formats=['%d.%m.%Y', ])


class Filtr2(forms.Form):

    znp = forms.CharField(required=False, label='Номер ЗНП', max_length=25)
    module_type = forms.ChoiceField(required=False, label='Тип модуля',
                                    choices=find_module_type)


class Sort(forms.Form):

    sorting = forms.ChoiceField(label='Сортировать по', choices=sorting_list)

IGBT_view/igbt/views.py
from django.views.generic import ListView, DetailView, RedirectView
from .models import IGBT_static_cold, IGBT_static_hot, IGBT_dinamic_cold, IGBT_dinamic_hot
import pickle
import base64
from django.views.generic.base import TemplateView, View
from pure_pagination.mixins import PaginationMixin
from .forms import Filtr, Filtr2, Sort, sorting_list
import datetime
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from io import BytesIO
import xlsxwriter
from django.views.generic.list import MultipleObjectMixin


class Home(RedirectView):

    url = '/home/'


class Start_page(TemplateView):

    template_name = 'igbt/home.html'

    def get_context_data(self, **kwargs):
        context = super(Start_page, self).get_context_data(**kwargs)
        context['title'] = 'IGBT'
        return context


class Page_of_choice(TemplateView):

    template_name = 'igbt/choice.html'

    def get_context_data(self, **kwargs):
        context = super(Page_of_choice, self).get_context_data(**kwargs)
        context['title'] = 'IGBT'
        return context


class Igbt_modules_Mixin(MultipleObjectMixin):

    sorting_list_part = [y[0] for y in sorting_list]
    context_object_name = 'znp_list'

    def get_context_data(self, **kwargs):

        context = super(Igbt_modules_Mixin, self).get_context_data(**kwargs)

        context['form1'] = self.form1
        context['form2'] = self.form2
        context['sort'] = self.sort
        context['in'] = self.panel_in
        return context

    def get_queryset(self):

        ob_set = self.model.objects.all()

        if self.request.method == 'GET' and len(self.request.GET) > 1:

            self.panel_in = 'in'
            form1 = Filtr(self.request.GET)
            form2 = Filtr2(self.request.GET)
            sort = Sort(self.request.GET)

            if form1.is_valid():
                self.form1 = form1
                if self.form1.cleaned_data['date_1']:
                    ob_set = ob_set.filter(
                        time__gte=self.form1.cleaned_data['date_1'])
                if self.form1.cleaned_data['date_2']:
                    ob_set = ob_set.filter(
                        time__lte=self.form1.cleaned_data['date_2'])
            else:
                self.form1 = Filtr()

            if form2.is_valid():
                self.form2 = form2
                if self.form2.cleaned_data['znp']:
                    ob_set = ob_set.filter(
                        znp__startswith=self.form2.cleaned_data['znp'])
                if self.form2.cleaned_data['module_type']:
                    ob_set = ob_set.filter(
                        module_type__exact=self.request.GET['module_type'])
            else:
                self.form2 = Filtr2()

            if sort.is_valid():
                self.sort = sort
                if self.sort.cleaned_data['sorting']:
                    ob_set = ob_set.order_by(self.request.GET['sorting'])
            else:
                self.sort = Sort()

            return ob_set

        else:
            self.panel_in = ''
            self.form1 = Filtr()
            self.form2 = Filtr2()
            self.sort = Sort()
            return ob_set


class Base_Igbt_modules(LoginRequiredMixin, PaginationMixin,
                        ListView, Igbt_modules_Mixin):

    login_url = '/login/'
    paginate_by = 15
    template_name = 'igbt/module_list.html'


class Igbt_static_cold_modules(Base_Igbt_modules):

    model = IGBT_static_cold

    def get_context_data(self, **kwargs):

        context = super(Igbt_static_cold_modules,
                        self).get_context_data(**kwargs)

        context['tps_cold'] = 'active'
        context['title'] = 'TPS 625 (cold)'
        return context


class Igbt_static_hot_modules(Base_Igbt_modules):

    model = IGBT_static_hot

    def get_context_data(self, **kwargs):

        context = super(Igbt_static_hot_modules,
                        self).get_context_data(**kwargs)

        context['tps_hot'] = 'active'
        context['title'] = 'TPS 625 (hot)'
        return context


class Igbt_dinamic_cold_modules(Base_Igbt_modules):

    model = IGBT_dinamic_cold

    def get_context_data(self, **kwargs):

        context = super(Igbt_dinamic_cold_modules,
                        self).get_context_data(**kwargs)

        context['dts_cold'] = 'active'
        context['title'] = 'DTS 758 (cold)'
        return context


class Igbt_dinamic_hot_modules(Base_Igbt_modules):

    model = IGBT_dinamic_hot

    def get_context_data(self, **kwargs):

        context = super(Igbt_dinamic_hot_modules,
                        self).get_context_data(**kwargs)

        context['dts_hot'] = 'active'
        context['title'] = 'DTS 758 (hot)'
        return context


class Base_Igbt_module(LoginRequiredMixin, DetailView):

    login_url = '/login/'
    template_name = 'igbt/module_results.html'

    def get_context_data(self, **kwargs):

        context = super(Base_Igbt_module, self).get_context_data(**kwargs)
        prot_obj = pickle.loads(base64.b64decode(
            context['object'].protocol_object))
        context['prot_obj'] = prot_obj
        context['title'] = context['object'].znp
        return context


class Igbt_static_cold_module(Base_Igbt_module):

    model = IGBT_static_cold


class Igbt_static_hot_module(Base_Igbt_module):

    model = IGBT_static_hot


class Igbt_dinamic_cold_module(Base_Igbt_module):

    model = IGBT_dinamic_cold


class Igbt_dinamic_hot_module(Base_Igbt_module):

    model = IGBT_dinamic_hot


class Xlsx_export(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):

        k = request.GET['path'].split('/')
        x = k[2].split('_')
        znp = k[3]

        model_name = '_'.join(('IGBT', x[0], x[1]))
        pr_tb = globals()[model_name].objects.get(znp=znp)
        filename = '_'.join((pr_tb.znp, pr_tb.module_type,
                             pr_tb.temperature, x[0].upper()))
        pr_ob = pickle.loads(base64.b64decode(pr_tb.protocol_object))
        response = HttpResponse(content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename='+filename+'.xlsx'
        xlsx_data = self.write_To_Excel(pr_ob, request)
        response.write(xlsx_data)
        return response

    def write_To_Excel(self, pr_ob, request):

        output = BytesIO()
        workbook = xlsxwriter.Workbook(output)

        worksheet_1 = workbook.add_worksheet("Results")
        worksheet_1.set_landscape()
        worksheet_1.set_margins(left=0.3, right=0.3, top=0.3, bottom=0.3)

        format_1 = workbook.add_format({'border': 1})
        format_2 = workbook.add_format({'border': 1, 'bold': True})
        format_2.set_text_wrap()
        format_2.set_align('top')
        format_3 = workbook.add_format({'left': 1})
        format_4 = workbook.add_format({'right': 1})
        format_5 = workbook.add_format({'left': 1, 'top': 1, 'bottom': 1})
        format_6 = workbook.add_format({'top': 1, 'right': 1, 'bottom': 1})
        format_7 = workbook.add_format({'right': 1, 'bottom': 1})
        format_8 = workbook.add_format({'top': 1, 'bottom': 1})
        format_9 = workbook.add_format({'bottom': 1})
        format_10 = workbook.add_format({'left': 1, 'bottom': 1})
        format_11 = workbook.add_format({'border': 1, 'bg_color': '#DCDCDC'})
        format_12 = workbook.add_format({'border': 1, 'bg_color': '#DCDCDC',
                                         'bold': True})

        worksheet_1.write(0, 0, '', format_5)
        worksheet_1.write(0, 1, 'Общие данные', format_8)
        worksheet_1.write(0, 2, '', format_6)
        worksheet_1.write(16, 0, '', format_10)
        worksheet_1.write(16, 2, '', format_7)
        worksheet_1.write(16, 1, '', format_9)

        for i in range(1, 16):
            worksheet_1.write(i, 0, '', format_3)
            worksheet_1.write(i, 2, '', format_4)

        worksheet_1.set_column('A:A', 1)
        worksheet_1.set_column('B:B', 32)
        worksheet_1.set_column('C:D', 1)

        worksheet_1.write('B3', 'Номер ЗНП', format_1)
        worksheet_1.write('B4', pr_ob.znp, format_2)
        worksheet_1.write('B6', 'Тип модуля', format_1)
        worksheet_1.write('B7', pr_ob.module_type, format_2)
        worksheet_1.write('B9', 'Температура', format_1)
        worksheet_1.write('B10', pr_ob.temperature, format_2)
        worksheet_1.write('B12', 'Дата измерения', format_1)

        date_format_str = 'dd/mm/yy hh:mm'
        date_format = workbook.add_format({'bold': True,
                                           'num_format': date_format_str,
                                           'align': 'left',
                                           'border': 1}
                                          )

        d = datetime.timedelta(seconds=+10800)
        naive_datetime = pr_ob.time+d
        naive_datetime = naive_datetime.replace(tzinfo=None)

        worksheet_1.write_datetime(12, 1, naive_datetime, date_format)

        worksheet_1.write('B15', 'Тип теста измерений', format_1)
        worksheet_1.write('B16', pr_ob.test_config, format_2)

        if request.GET['add']:

            worksheet_1.write(18, 0, '', format_5)
            worksheet_1.write(18, 1, 'Данные пользователя', format_8)
            worksheet_1.write(18, 2, '', format_6)
            worksheet_1.write(26, 0, '', format_10)
            worksheet_1.write(26, 2, '', format_7)
            worksheet_1.write(26, 1, '', format_9)

            for i in range(19, 26):
                worksheet_1.write(i, 0, '', format_3)
                worksheet_1.write(i, 2, '', format_4)
            try:
                name = '{0} {1}. {2}.'.format(
                    request.user.last_name,
                    request.user.first_name[0],
                    request.user.profile.patronymic[0])
            except:

IGBT_view/igbt/templates/igbt/choice.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block home %}
<!-- Team -->
    <section id="team" class="team">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="title-box">
                        <h2 class="section-title">Выбор типа измерений</h2>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
                    <div class="linkblock " onclick="location.href='{% url 'igbt:igbt_static_cold_modules' %}';">
                        <div class="team-box">
                            <img class="img-responsive img-full" src="{% static 'images/TPS_625_.jpg' %}" alt="team">
                            <div class="team-detail">
                                <ul>
                                    <li><h3>TPS 625</h3></li>
                                    <li><h4>cold</h4></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
                    <div class="linkblock " onclick="location.href='{% url 'igbt:igbt_static_hot_modules' %}';">
                        <div class="team-box">
                            <img class="img-responsive img-full" src="{% static 'images/TPS_625_hot_.jpg' %}" alt="team">
                            <div class="team-detail">
                                <ul>
                                    <li><h3>TPS 625</h3></li>
                                    <li><h4>hot</h4></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>                <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
                    <div class="linkblock " onclick="location.href='{% url 'igbt:igbt_dinamic_cold_modules' %}';">
                        <div class="team-box">
                            <img class="img-responsive img-full" src="{% static 'images/DTS_758_.jpg' %}" alt="team">
                            <div class="team-detail">
                                <ul>
                                    <li><h3>DTS 758</h3></li>
                                    <li><h4>cold</h4></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
                    <div class="linkblock " onclick="location.href='{% url 'igbt:igbt_dinamic_hot_modules' %}';">
                        <div class="team-box">
                            <img class="img-responsive img-full" src="{% static 'images/DTS_758_hot_.jpg' %}" alt="team">
                            <div class="team-detail">
                                <ul>
                                    <li><h3>DTS 758</h3></li>
                                    <li><h4>hot</h4></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{%endblock%}    
{% block css %}              
<style>  
.linkblock {
cursor:pointer;
}
</style>
{%endblock%}  

IGBT_view/igbt/templates/igbt/home.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block home %}

<!-- Header Section -->
    <header id="header" class="header overlay-light">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="intro-box c-table">
                        <div class="intro ct-cell">
                            <h1>IGBT</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    
 <!-- Consultation -->
    <section id="consultation" class="consultation">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="title-box">
                        <h2 class="section-title">Просмотр результатов измерений IGBT модулей</h2>
                        <p class="section-subtitle">Данное приложение позволяет просматривать 
                                                    результаты измерений IGBT модулей, 
                                                    проведённых на испытательном 
                                                    оборудовании TPS 625 и DTS 758.</p>
                    </div>
                </div>
                <center>
                    <img src="{% static 'images/igbt.jpg' %}" class="img-rounded" width="60%" height="60%">
                </center>
                <br>
                <div class="col-sm-4 col-sm-offset-4">
                    <a class="btn btn-default btn-block btn-cn" href="{% url 'igbt:igbt_choice' %}">Просмотр результатов</a>
                </div>
            </div>
        </div>
    </section>
{%endblock%}

IGBT_view/igbt/templates/igbt/module_list.html
{% extends 'base/main.html' %}

{% load staticfiles %}

{% load i18n %}

{% block static_igbt %}
<!-- Team -->
<section id="team" class="team">
<div class="panel-group" id="accordion">
    <div class="panel panel-default">
    
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                Поиск
                </a>
            </h4>
        </div>
        
        <div id="collapseOne" class="panel-collapse collapse {{in}}">
            <div class="panel-body">
                                 
                <form id='form' action="{{request.path}}" method="get">
                    
                    <div class="row">
                    
                        <div class="col-sm-12 col-md-6 col-lg-4" >                                
                            <div class="well">    
                                <div class="hero-unit">

                                    <table class="table table-condensed" style="table-layout: fixed;">
                                    <caption>Критерии поиска №1</caption>
                                    {{ form1.as_table }}
                                    </table >
                                    
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-sm-12 col-md-6 col-lg-4" >
                            <div class="well">    
                                <div class="hero-unit">
                                
                                    <table class="table table-condensed" style="table-layout: fixed;">
                                    <caption>Критерии поиска №2</caption>
                                    {{ form2.as_table }}
                                    </table >
                                       
                                </div>                                
                            </div>                                    
                        </div>
                        
                        <div class="col-sm-12 col-md-6 col-lg-4" >
                            <div class="well">    
                                <div class="hero-unit">
                                
                                    <table class="table table-condensed" style="table-layout: fixed;">
                                    <caption>Сортировка</caption>
                                    {{ sort.as_table }}
                                    </table >
                                    
                                    <center>    
                                        <input class="btn btn-default btn-cn" type="submit" value="Поиск/Сортировка" >
                                        <input id='reset' class="btn btn-default btn-cn" type="button" value ="Сбросить">                                   
                                    </center> 
                                    
                                </div>                                
                            </div>                                    
                        </div>  
                        
                    </div>                      
                    
                </form>

            </div>
        </div>
        
    </div>  
</div>

<div style='overflow-y:auto; width:100%;'>    
    <table class="table table-condensed"  >
        <caption>Таблица протоколов</caption>
        <thead>
        
            <tr>
                <th>ЗНП</th>
                <th>Дата</th>
                <th>Тип модуля</th>
                <th>Температура</th>            
                <th>Тип теста измерений</th>
            </tr>
            
        </thead>
        <tbody>
        
            {% for znp in znp_list %}
                <tr class="linkblock team-box" onclick="window.open('{{request.path}}{{znp.znp}}')">
                <td>{{ znp.znp }}</a></td>
                <td>{{ znp.time }}</td>     
                <td>{{ znp.module_type }}</td>  
                <td>{{ znp.temperature }}</td>          
                <td>{{ znp.test_config }}</td>                  
                </tr>
            {% endfor %}
            
        </tbody>
    </table>    
</div>

<center>
    <div class="pagination">
        <ul class="pagination pagination-sm">
        
            {% if page_obj.has_previous %}
                <li><a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&laquo;</a></li>
            {% else %}
                <li class="disabled"><a>&laquo;</a></li>
            {% endif %}            
            {% for page in page_obj.pages %}
                {% if page %}
                    {% ifequal page page_obj.number %}
                        <li class="active"><span class="current page">{{ page }}</span></li>
                    {% else %}
                         <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li><a>...</a></li>
                {% endif %}                
            {% endfor %}            
            {% if page_obj.has_next %}
                <li><a href="?{{ page_obj.next_page_number.querystring }}" class="prev">&raquo;</a></li>
            {% else %}
                <li class="disabled"><a>&raquo;</a></li>
            {% endif %}
        </ul>
    </div>
</center>
</section>
{%endblock%}

{% block scripts %}
<script type="text/javascript" src="{% static 'jquery/jquery-ui.js' %}"></script>
<script type="text/javascript" src="{% static 'jquery/datepicker-ru.js' %}"></script>

<script type="text/javascript">

$(document).ready(function() {

    $( function() {
        $( "#id_date_1" ).datepicker($.datepicker.regional[ "ru" ]);
    } );

    $( function() {
        $( "#id_date_2" ).datepicker($.datepicker.regional[ "ru" ]);
    } );

    var dates = $( "#id_date_1, #id_date_2" ).datepicker({
        maxDate: new Date(),
        minDate: new Date("1991-02-13"),
        onSelect: function( selectedDate ) {
            var option = this.id == "id_date_1" ? "minDate" : "maxDate",
            instance = $( this ).data( "datepicker" ),
            date = $.datepicker.parseDate(
                instance.settings.dateFormat ||
                $.datepicker._defaults.dateFormat,
                selectedDate, instance.settings );
            dates.not( this ).datepicker( "option", option, date );}
    });

    $( "#id_znp" ).autocomplete({
        source: function( request, response ) {
        $.ajax( {
            url: "/json_znp/",
            data: {
                term: request.term,
                path: "{{request.path}}"
                    },
        success: function( data ) {
            response( data );
                                            }
                } );
                                                            },
        minLength: 2,
                                            } );

    $('#reset').bind('click', function() {
      $('#id_date_1').val('');
      $('#id_date_2').val('');
      $('#id_znp').val('');
      $('#id_module_type option').removeAttr('selected');
      $('#id_module_type option:first').attr('selected', 'selected');
      $('#id_sorting option').removeAttr('selected');
      $('#id_sorting option:first').attr('selected', 'selected');
    });
} );

</script>

{%endblock%}

{% block css %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<style>  
.well {
border-radius: 0px;
background-color: #F2EEED;
}
.panel-default>.panel-heading {
background-color: #F2EEED;
}
.panel-group .panel {
border-radius: 0px;
}
.linkblock {
cursor:pointer;
}
.ui-autocomplete-loading {
background: white url("{% static 'images/ui-anim_basic_16x16.gif' %}") right center no-repeat;
}
input {
border-color: transparent;
box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
}
select {
border-color: transparent;
box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
}
.pagination>.active>a, .pagination>.active>a:focus, .pagination>.active>a:hover, .pagination>.active>span, .pagination>.active>span:focus, .pagination>.active>span:hover {
    background-color: #31436b;
    border-color: #31436b;
}
.pagination>li>a:focus, .pagination>li>a:hover, .pagination>li>span:focus, .pagination>li>span:hover {
    border-color: #31436b;
}
.pagination>li>a, .pagination>li>span {
    color: #31436b;
    border: 1px solid #31436b;
}
.pagination-sm>li:first-child>a, .pagination-sm>li:first-child>span {
    border-top-left-radius: 0px;
    border-bottom-left-radius: 0px;
}
.pagination-sm>li:last-child>a, .pagination-sm>li:last-child>span {
    border-top-right-radius: 0px;
    border-bottom-right-radius: 0px;
}

</style> 
{%endblock%}