IGBT_view/IGBT_view/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from igbt.views import Home


urlpatterns = [
    url(r'^$', Home.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('igbt.urls')),
]

IGBT_view/igbt/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'igbt'

urlpatterns = [
    url(r'login/$', auth_views.login, name='login'),
    url(r'logout/$', auth_views.logout,
        {'template_name': 'registration/logout.html'}, name='logout'),
    url(r'password_change/$', auth_views.password_change,
        {'post_change_redirect': 'igbt:password_change_done',
         'template_name': 'registration/password_change.html'},
        name='password_change'),
    url(r'password_change/done/$', auth_views.password_change_done,
        {'template_name': 'registration/password_change_successfully.html'},
        name='password_change_done'),
    url(r'json_znp/$', json_znp),
    url(r'home/$', Start_page.as_view(), name='home'),
    url(r'igbt/$', Page_of_choice.as_view(), name='igbt_choice'),
    url(r'igbt/static_cold_measurements/$', Igbt_static_cold_modules.as_view(),
        name='igbt_static_cold_modules'),
    url(r'igbt/static_hot_measurements/$', Igbt_static_hot_modules.as_view(),
        name='igbt_static_hot_modules'),
    url(r'igbt/dinamic_cold_measurements/$',
        Igbt_dinamic_cold_modules.as_view(), name='igbt_dinamic_cold_modules'),
    url(r'igbt/dinamic_hot_measurements/$', Igbt_dinamic_hot_modules.as_view(),
        name='igbt_dinamic_hot_modules'),
    url(r'igbt/static_cold_measurements/(?P<pk>\d+_\d{4}(_\d){0,1})/$',
        Igbt_static_cold_module.as_view(), name='igbt_static_cold_module'),
    url(r'igbt/static_hot_measurements/(?P<pk>\d+_\d{4}(_\d){0,1})/$',
        Igbt_static_hot_module.as_view(), name='igbt_static_hot_module'),
    url(r'igbt/dinamic_cold_measurements/(?P<pk>\d+_\d{4}(_\d){0,1})/$',
        Igbt_dinamic_cold_module.as_view(), name='igbt_dinamic_cold_module'),
    url(r'igbt/dinamic_hot_measurements/(?P<pk>\d+_\d{4}(_\d){0,1})/$',
        Igbt_dinamic_hot_module.as_view(), name='igbt_dinamic_hot_module'),
    url(r'xlsx_export/$', Xlsx_export.as_view(), name='xlsx'),
]

IGBT_view/templates/base/main.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>{{title}}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <!-- Bootstrap -->
    <link rel='stylesheet' type='text/css' href="{% static 'Bootstrap-3.3.7/css/bootstrap.min.css' %}"/>
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    
    {% block css %}{%endblock%}
    <style> 
    .nav a{
        font-size: 12px;
    </style>  
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="{% static 'jQuery-3.2.1/jquery-3.2.1.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="{% static 'Bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
   

    {% block scripts %}{%endblock%}
  
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>

        <!-- NavigationBar Section -->
            <nav id='nav' class="navbar navbar-default navbar-fixed-top">
                <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a style='font-size: 40pt;' class="navbar-brand" href="/">IGBT</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="main-navbar">
                  <ul class="nav navbar-nav navbar-left">
                    <li class="{{tps_cold}}" ><a href="{% url 'igbt:igbt_static_cold_modules' %}">TPS 625 (cold) </a></li>
                    <li class="{{tps_hot}}" ><a href="{% url 'igbt:igbt_static_hot_modules' %}">TPS 625 (hot)</a></li>
                    <li class="{{dts_cold}}" ><a href="{% url 'igbt:igbt_dinamic_cold_modules' %}">DTS 758 (cold)</a></li>
                    <li class="{{dts_hot}}" ><a href="{% url 'igbt:igbt_dinamic_hot_modules' %}">DTS 758 (hot)</a></li>
                  </ul>
                  
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a style='font-size: 14pt;' href="#" class="dropdown-toggle" data-toggle="dropdown"><b>{{user.username}}</b><span class="caret"></span></a>                   
                        <ul class="dropdown-menu">                    
                            <li><a href="{% url 'igbt:password_change' %}">Сменить пароль</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'igbt:logout' %}">Выйти</a></li>                        
                        </ul>              
                    </li>
                </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a style='font-size: 15pt;'  href="{% url 'igbt:login' %}" ><b>Войти</b></a>
                        </li>
                    </ul>
                {% endif %}                  
                </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        {% block home %}{%endblock%}  
        {% block static_igbt %}{%endblock%}      
        {% block login_logout %}{%endblock%}      
        {% block password_change %}{%endblock%}      
        <!-- Footer -->
            <footer class="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6">
                            <p>
                                @ ПРОТОН-ЭЛЕКТРОТЕКС
                            </p>
                        </div>
                    </div>
                </div>
            </footer>          
</body>
</html>